name=BLECommands
version=1.0.0
author=Andrey Rodin
maintainer=Andrey Rodin <andrey.val.rodin@gmail.com>
sentence=Simple Arduino BLE library implementing text-based command/response protocol.
paragraph=Developed as a server-side analogue of the BleCommands .NET library - ideal for controlling Arduino projects from .NET applications.
category=Communication
url=https://github.com/andrey-val-rodin/BleCommands.Arduino/
architectures=*
includes=BLECommands.h
depends=ArduinoBLE
